# Generated by Django 3.1.14 on 2023-03-12 16:44

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('nd_date', unixtimestampfield.fields.UnixTimeStampField()),
                ('s_date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('not_date', models.DateTimeField()),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.resource')),
            ],
        ),
    ]
